### ISSUE TITLE
Please consider hosting the examples+solutions in a git repository

### ISSUE THREAD

**Issue by coolharsh55** [aidhog/webofdatabook#1]
Currently, the examples+solutions are provided as a zip download at http://webofdatabook.org/
By providing these in a git repository, it is easier to copy (fork), iterate, save and share changes, and also enables others to build upon them (e.g. package ready-to-deploy environments).

Thanks for the book and code : )

**Comment by aidhog** [comment]
Thanks for the suggestion! These are now included in the current github repository. :)
